apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: ssh-keys-v
        secret:
          secretName: ssh-keys
      containers:
        - name: nginx-server
          image: custom_nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 22
            - containerPort: 443
          env:
          - name: HOST_PHPMYADMIN
            value: phpmyadmin
          volumeMounts:
          - name: ssh-keys-v
            mountPath: "/.ssh"
      
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 22
    targetPort: 22
    protocol: TCP
    name: ssh
  selector:
    app: nginx