apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: influxdb
spec:
  ports:
    - port: 35000
  selector:
    app: influxdb
    tier: telegraf
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: influxdb
    tier: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
        tier: telegraf
    spec:
      serviceAccountName: telegraf-account
      containers:
      - image: telegraf_alpine
        imagePullPolicy: Never
        name: telegraf
        ports:
        - containerPort: 35000
          name: telegraf
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: telegraf-account
  namespace: default

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-account
  labels:
    app: telegraf
